import 'dart:typed_data';

import 'package:bike_navigation/services/ble_protocol.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('projectLatLon', () {
    // Reference values generated by maps/build_map.py's project() for the same
    // lat/lon inputs — these two implementations must agree, or route points
    // sent over BLE won't line up with the roads/water baked into map.bin.
    test('origin projects to (0, 0)', () {
      final p = projectLatLon(originLat, originLon);
      expect(p.x, closeTo(0.0, 1e-9));
      expect(p.y, closeTo(0.0, 1e-9));
    });

    test('matches build_map.py for a nearby point', () {
      final p = projectLatLon(51.4832, -0.1737);
      expect(p.x, closeTo(-67.18929467975293, 1e-6));
      expect(p.y, closeTo(529.7447483229193, 1e-6));
    });

    test('matches build_map.py for a farther, mixed-direction point', () {
      final p = projectLatLon(51.4700, -0.1500);
      expect(p.x, closeTo(1574.1119359708568, 1e-6));
      expect(p.y, closeTo(-938.0282833849955, 1e-6));
    });
  });

  group('buildTelemetry', () {
    test('packs to exactly 12 bytes matching the wire format', () {
      final bytes = buildTelemetry(xMeters: 123.45, yMeters: -67.89, headingDeg: 90.1, mode: modeNav);
      expect(bytes.length, 12);
      final data = ByteData.sublistView(bytes);
      expect(data.getUint8(0), kPacketTelemetry);
      expect(data.getInt32(1, Endian.little), 12345); // 123.45m -> 12345cm
      expect(data.getInt32(5, Endian.little), -6789); // -67.89m -> -6789cm
      expect(data.getInt16(9, Endian.little), 901); // 90.1deg -> 901 decidegrees
      expect(data.getUint8(11), modeNav);
    });
  });

  group('buildRouteStart', () {
    test('packs to exactly 3 bytes', () {
      final bytes = buildRouteStart(250);
      expect(bytes.length, 3);
      final data = ByteData.sublistView(bytes);
      expect(data.getUint8(0), kPacketRouteStart);
      expect(data.getUint16(1, Endian.little), 250);
    });
  });

  group('buildRouteChunk', () {
    test('packs header + count*8 bytes, little-endian', () {
      final points = [(x: 10.0, y: 20.0), (x: -5.5, y: 0.0)];
      final bytes = buildRouteChunk(3, points);
      expect(bytes.length, 4 + points.length * 8);
      final data = ByteData.sublistView(bytes);
      expect(data.getUint8(0), kPacketRouteChunk);
      expect(data.getUint16(1, Endian.little), 3);
      expect(data.getUint8(3), 2);
      expect(data.getInt32(4, Endian.little), 1000); // 10.0m -> 1000cm
      expect(data.getInt32(8, Endian.little), 2000); // 20.0m -> 2000cm
      expect(data.getInt32(12, Endian.little), -550); // -5.5m -> -550cm
      expect(data.getInt32(16, Endian.little), 0);
    });

    test('handles an empty chunk', () {
      final bytes = buildRouteChunk(0, []);
      expect(bytes.length, 4);
    });
  });

  group('buildRouteEnd / buildRouteClear', () {
    test('are single-byte packets with the right type', () {
      expect(buildRouteEnd(), Uint8List.fromList([kPacketRouteEnd]));
      expect(buildRouteClear(), Uint8List.fromList([kPacketRouteClear]));
    });
  });
}
