#!/usr/bin/env python3
"""Emit map.bin as a C byte array the firmware can compile straight into
flash — no filesystem/SD card needed since the data comfortably fits in
program flash."""
from pathlib import Path

MAP_BIN = Path(__file__).parent / "map.bin"
OUT = Path(__file__).parent.parent / "firmware" / "src" / "map_data.h"


def main():
    data = MAP_BIN.read_bytes()
    lines = []
    lines.append("// Generated by maps/export_firmware.py from maps/map.bin — do not edit by hand.")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"static const uint32_t MAP_DATA_LEN = {len(data)};")
    lines.append("static const uint8_t MAP_DATA[] = {")
    row = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02x}")
        if len(row) == 20:
            lines.append(",".join(row) + ",")
            row = []
    if row:
        lines.append(",".join(row) + ",")
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB source, {len(data) / 1024:.1f} KB data)")


if __name__ == "__main__":
    main()
